version: '3.5'
services:
  crdb:
    image: 'cockroachdb/cockroach:latest-v23.1'
    command: >
      start-single-node --certs-dir=/cockroach/certs --advertise-addr=0.0.0.0 --http-addr=0.0.0.0:${HTTP_PORT}
    environment:
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=suraj
    volumes:
      - './cockroach-data/crdb:/cockroach/cockroach-data'
      - './cockroach-certs:/cockroach/certs'
      - './init-cockroach.sh:/docker-entrypoint-initdb.d/init-cockroach.sh'
    ports:
      - "${SQL_PORT}:26257"
      - "${HTTP_PORT}:8081"

